### ISSUE TITLE
Type mismatch error

### ISSUE THREAD

**Issue by saintjab** [howljs/hl_image_picker#45]
I am trying to use the latest version 1.2.14 but getting Android compile time error:

hl_image_picker_android/android/src/main/kotlin/com/howl/hl_image_picker/ImageFileCompressEngine.kt:70:74 Type mismatch: inferred type is OutputStream? but OutputStream was expected

Any idea how to resolve it?

**Comment by luwei888** [comment]
Did you solve the problem?

**Comment by jazzbpn** [comment]
??

**Comment by adlanarifzr** [comment]
I use the PR repo temporarily
```yaml
  hl_image_picker_android:
    git:
      url: https://github.com/miraclebg/hl_image_picker.git
      path: hl_image_picker_android
```
